### ISSUE TITLE
Problem with pip install

### ISSUE THREAD

**Issue by RAShaw-sci** [adsabs/ads-examples#4]
After running `pip install ads` in my conda base environment (set up for python 3.6), I encounter an error, which is given below. Is there a problem on my machine (OSX 10.12.6) or my environment that could be causing this? 

Error trace: 
Collecting ads
  Using cached https://files.pythonhosted.org/packages/91/5a/caeec9ab5b746402e1d0181abf9379838466abe9ad3809d5b817de1b3e57/ads-0.12.3.tar.gz
Requirement already satisfied: six in /Users/shaw/anaconda3/lib/python3.6/site-packages (from ads) (1.12.0)
Requirement already satisfied: requests in /Users/shaw/anaconda3/lib/python3.6/site-packages (from ads) (2.22.0)
Collecting httpretty==0.8.10
  Using cached https://files.pythonhosted.org/packages/e2/25/603bc6b096385b02184cc94f9088fcc06abd9398d0975bbbce97a8989ab5/httpretty-0.8.10.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /Users/shaw/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/setup.py'"'"'; __file__='"'"'/private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/pip-egg-info
         cwd: /private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/setup.py", line 86, in <module>
        version=read_version(),
      File "/private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/setup.py", line 46, in read_version
        finder.visit(ast.parse(local_file('httpretty', '__init__.py')))
      File "/private/var/folders/ts/y5m5w9gx47d5ft3bzfytr5zh0000zq/T/pip-install-ad34j38k/httpretty/setup.py", line 78, in <lambda>
        open(os.path.join(os.path.dirname(__file__), *f)).read()
      File "/Users/shaw/anaconda3/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 133: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jonnybazookatone** [comment]
Without trying it, it looks like httpretty is not installing correctly.

Try:
```
pip install --no-cache-dir ads
```

**Comment by RAShaw-sci** [comment]
Thanks for the suggestion. Unfortunately, I get the same error.

**Comment by jonnybazookatone** [comment]
what output do you get for `echo $LC_ALL`?

https://github.com/gabrielfalcao/HTTPretty/issues/223

**Comment by RAShaw-sci** [comment]
Ah, thanks for the pointer to that discussion! So I did the following from the shell:

- `export LC_ALL="en_US.utf-8"`

and the install worked fine.
